FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /app
COPY . ./
RUN rm ./WSM.Server/appsettings.json
RUN rm ./WSM.Server/appsettings.Development.json
RUN dotnet restore
RUN dotnet publish "./WSM.Server/WSM.Server.csproj" -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS final
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT [ "dotnet", "WSM.Server.dll" ]